### ISSUE TITLE
HTML5 target broken

### ISSUE THREAD

**Issue by Joncom** [luboslenco/video_example_kha#1]
See https://github.com/Kode/Kha/issues/970

Wasn't sure if this was an issue with the example, or Kha itself...

**Comment by luboslenco** [comment]
It's Chrome changing things, should be ok now.. 😛 https://github.com/luboslenco/video_example_kha/commit/1712b424bc07d1162bc79186ee1bdda3e92487c9.

**Comment by Joncom** [comment]
Confirmed, HTML5 works OK now.
