### ISSUE TITLE
iOS target broken

### ISSUE THREAD

**Issue by Joncom** [luboslenco/video_example_kha#2]
![screen shot 2019-01-23 at 2 43 56 pm](https://user-images.githubusercontent.com/1667179/51590689-6aede900-1f1d-11e9-9b9f-b46abadf8775.png)

**Comment by Joncom** [comment]
This error seems specific to Metal (not OpenGL) by the way.

**Comment by luboslenco** [comment]
Merge with issue https://github.com/Kode/Kha/issues/972.
